[_]
schema-version = "0.2"

[[io.buildpacks.group]]
id = "heroku/nodejs"

[[io.buildpacks.group]]
id = "heroku-community/static"

[web]
processes = [{ type = "web", command = "npx serve -s dist -l $PORT" }]

[com.heroku.static-web-server]
root = "dist"
index = "index.html"